# Docker compose file for building docker images and running locally

version: '3.8'

services:
  book_catalog:
    build:
     context: ./book_catalog
     dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=postgresql://sit722week7taskp_user:WH5Se3wBue7Yc3ngoY0JvHZNfPvozTeN@dpg-crl5egd6l47c73frsss0-a.oregon-postgres.render.com/sit722week7taskp
    networks:
      - app-networks

  inventory_management:
    build:
     context: ./inventory_management
     dockerfile: Dockerfile
    ports:
      - "8002:80"
    environment:
     - DATABASE_URL=postgresql://sit722week7taskp_user:WH5Se3wBue7Yc3ngoY0JvHZNfPvozTeN@dpg-crl5egd6l47c73frsss0-a.oregon-postgres.render.com/sit722week7taskp
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge